spring.application.name=campusFlow

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/campus}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:j060805.}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

stripe.secret-key=${STRIPE_SECRET_KEY:}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:whsec_pendiente}
stripe.price-pago-unico=${STRIPE_PRICE_PAGO_UNICO:}
stripe.price-plan-individual=${STRIPE_PRICE_PLAN_INDIVIDUAL:}
stripe.url-exito=http://localhost:8080/pago-exitoso
stripe.url-cancelado=http://localhost:8080/pago-cancelado

JWT_SECRET=LF+6rT6GMy2JLPIVY7tcAGZLnotsJovl81UQCo1aDJI=
